# Generated by Django 5.1.2 on 2024-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='statuse',
        ),
        migrations.AddField(
            model_name='prices',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
